# Generated by Django 5.2.6 on 2025-09-27 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-creado_en']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('user', 'nombre')},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_finanzas.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('user', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo',
        ),
    ]
