# Generated by Django 5.2.6 on 2025-09-30 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_finanzas', '0002_alter_categoria_options_alter_cuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('CHEQUES', 'Cheques/Corriente'), ('AHORROS', 'Ahorros'), ('CREDITO', 'Tarjeta de Crédito'), ('EFECTIVO', 'Efectivo/Billetera'), ('INVERSION', 'Inversión')], default='AHORROS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_inicial',
        ),
    ]
