# Generated by Django 5.2.7 on 2025-10-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_finanzas', '0002_rename_balance_cuenta_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('AHORROS', 'Ahorros'), ('CHEQUES', 'Cheques/Corriente'), ('INVERSION', 'Inversión'), ('TARJETA', 'Tarjeta de Crédito'), ('EFECTIVO', 'Efectivo'), ('PRESTAMO', 'Préstamo Personal/Deuda'), ('HIPOTECA', 'Hipoteca'), ('AUTO', 'Préstamo de Auto'), ('RETIRO', 'Cuenta de Retiro/Pensión'), ('CRYPTO', 'Criptomonedas'), ('CDT', 'Certificado de Depósito (CDT)'), ('WALLET', 'Billetera Digital/PayPal'), ('METAS', 'Ahorro para Metas Específicas'), ('ACTIVO_FIJO', 'Activo Fijo (Valor Neto)'), ('COBRO', 'Cuentas por Cobrar')], max_length=15),
        ),
    ]
