# Generated by Django 5.2.6 on 2025-10-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_finanzas', '0003_alter_categoria_options_alter_cuenta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('AHORROS', 'Ahorros'), ('CHEQUES', 'Cheques/Corriente'), ('INVERSION', 'Inversión'), ('TARJETA', 'Tarjeta de Crédito'), ('EFECTIVO', 'Efectivo')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha_creacion',
        ),
    ]
