# Generated by Django 5.2.7 on 2025-10-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_finanzas', '0003_alter_cuenta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='es_transferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='transaccion_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='par_transferencia', to='mi_finanzas.transaccion'),
        ),
    ]
