site_name: Manual de Usuario - MiFinanzas
site_description: Guía completa para el uso de la aplicación de gestión financiera.
repo_url: 

theme: readthedocs # Tema funcional y estable

nav:
  - Inicio: index.md # RUTA FINAL Y CORRECTA: Apunta al archivo index.md
