site_name: Manual de Usuario - MiFinanzas
site_description: Guía completa para el uso de la aplicación de gestión financiera.
repo_url: 

theme: readthedocs # Tema funcional
  
nav:
  - Inicio: manual_de_usuario.md # RUTA CORREGIDA: Apunta directamente al archivo.
